env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - jest
  - 'prettier'
  - '@typescript-eslint'
rules: {
  'no-console': ['error', { allow: ['warn', 'error']}],
  'jest/consistent-test-it': 'error',
   'no-use-before-define': 'off',
   '@typescript-eslint/no-use-before-define': ['error'],
    // note you must disable the base rule as it can report incorrect errors
   "indent": "off",
  "@typescript-eslint/indent": ["error"]
}
