env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'
  - standard
  - 'prettier-standard'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - react-hooks
  - jest
  - prettier
  - '@typescript-eslint'
rules: {
  'no-console': ['error', { allow: ['warn', 'error']}],
  'jest/consistent-test-it': 'error',
  'no-use-before-define': 'off',
  '@typescript-eslint/no-use-before-define': ['error'],
  'react-hooks/rules-of-hooks': 'error',
  'react-hooks/exhaustive-deps': 'error',
  'prettier/prettier': 'error'
}
